#!/bin/sh
bucket=xxxx-test
endpoint=https://oos.cloudgouv-eu-west-1.outscale.com
profile=xxxxxxx
key=./test.csv
key2=test.csv

echo : "création du bucket"
sleep 2
aws s3api create-bucket --bucket $bucket --object-lock-enabled-for-bucket --profile $profile --endpoint $endpoint 
echo : "ajout du lock dans le bucket"
aws s3api put-object-lock-configuration --profile $profile --endpoint $endpoint --bucket $bucket --object-lock-configuration '{ "ObjectLockEnabled": "Enabled", "Rule": { "DefaultRetention": { "Mode": "COMPLIANCE", "Days": 1 }}}'
sleep 5
echo "vérification du lock"
aws s3api get-object-lock-configuration --profile $profile --endpoint $endpoint --bucket $bucket
sleep 10
echo "upload de l'objet dans le bucket"
aws s3api put-object --bucket $bucket --key $key --profile $profile --endpoint $endpoint
echo "list object"
sleep 2
aws s3api list-objects --bucket $bucket --profile $profile --endpoint $endpoint
sleep 10
echo "suppression de l'objet"
aws s3api delete-object --bucket $bucket --profile $profile --endpoint $endpoint --key $key2
sleep2
echo "vérification si l'objet est bien supprimé"
aws s3api list-objects --bucket $bucket --profile $profile --endpoint $endpoint
#sleep 10
#aws s3api head-object --bucket $bucket --key $key --profile $profile --endpoint $endpoint
#sleep 5
#aws s3api delete-objects --bucket $bucket --delete "$(aws s3api list-object-versions --bucket $bucket --output=json --query='{Objects: Versions[].{Key:Key,VersionId:VersionId}}' --endpoint $endpoint)" --endpoint $endpoint

